version: "3.9"
services:
  # api:
  #   restart: always
  #   build: .
  #   ports: 
  #     - 3000:3000
  #   networks:
  #     - local
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - local
    ports: 
      - 3333:3306
    volumes: 
      - ./data:/var/lib/mysql
  cache:
    restart: always
    image: redis
    ports: 
      - 6379:6379
    networks: 
      - local
networks:
  local: